services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    aintreallydown\ContractTypeBundle\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/ContractTypeBundle.php'